name: Python test

on:
  pull_request:
    branches:
    - main
    - develop
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Lambda runtime
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.lock
      - name: Test with pytest
        run: |
          pytest --cov=resources/lambda/src resources/lambda/
